### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by drexseoj** [yahoo/react-dnd-touch-backend#67] opened 2017-05-11 10:15 UTC
We are getting the following error on latest version 0.3.9 and we are using node.js version v6.2.2
```
/node_modules/react-dnd-touch-backend/dist/Touch.js:44
var elementsFromPoint = (document && document.elementsFromPoint || function (x, y) {
                         ^

ReferenceError: document is not defined
    at Object.<anonymous> (/www/node_modules/react-dnd-touch-backend/dist/Touch.js:44:26)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/www/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)

```

**Comment by JoaoMosmann** [comment] 2017-05-11 15:33
Duplicate of #62

**Closed by JoaoMosmann** 2017-05-11 15:33 UTC
Labels: duplicate
